import Head from "next/head";

import PageHeader from "../../components/PageHeader";
import Categories from "../../components/Categories";
import Presentation from "../../components/Presentation";

export default function Headphones() {
  return (
    <>
      <Head>
        <title>Headphones – audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader />

      <section>
        <Categories />
        <Presentation />
      </section>
    </>
  );
}
