import Head from "next/head";
import Link from "next/link";

export default function Checkout() {
  return (
    <>
      <Head>
        <title>Checkout – audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="go-back">
        <Link href="/">
          <a className="btn__go-back">Go back</a>
        </Link>

        <div className="checkout">
          <div className="left">
            <h1>Checkout</h1>

            <div className="checkout__inputs">
              <p>Billing details</p>

              <div className="checkout__inputs--split">
                <div className="checkout__input">
                  <label htmlFor="">Name</label>
                  <input type="text" name="" id="" placeholder="Alexei Ward" />
                </div>

                <div className="checkout__input">
                  <label htmlFor="">Email Address</label>
                  <input
                    type="email"
                    name=""
                    id=""
                    placeholder="alexei@mail.com"
                  />
                </div>

                <div className="checkout__input">
                  <label htmlFor="">Phone Number</label>
                  <input
                    type="tel"
                    name=""
                    id=""
                    placeholder="+1 202-555-0136"
                  />
                </div>
              </div>
            </div>

            <div className="checkout__inputs">
              <p>Shipping info</p>

              <div className="checkout__input">
                <label htmlFor="">Address</label>
                <input
                  type="text"
                  name=""
                  id=""
                  placeholder="1137 Williams Avenue"
                />
              </div>

              <div className="checkout__inputs--split">
                <div className="checkout__input">
                  <label htmlFor="">ZIP Code</label>
                  <input type="number" name="" id="" placeholder="10001" />
                </div>

                <div className="checkout__input">
                  <label htmlFor="">City</label>
                  <input type="text" name="" id="" placeholder="New York" />
                </div>

                <div className="checkout__input">
                  <label htmlFor="">Country</label>
                  <input
                    type="text"
                    name=""
                    id=""
                    placeholder="United States"
                  />
                </div>
              </div>
            </div>

            <p>Payment details</p>
          </div>

          <div className="summary">
            <h2>Summary</h2>

            <div className="summary__prices">
              <div className="summary__price">
                <p>Total</p>
                <p>$ X</p>
              </div>

              <div className="summary__price">
                <p>Shipping</p>
                <p>$ X</p>
              </div>

              <div className="summary__price">
                <p>Vat (Included)</p>
                <p>$ X</p>
              </div>

              <div className="summary__price">
                <p>Grand total</p>
                <p>
                  <span>$ X</span>
                </p>
              </div>
            </div>

            <Link href="">
              <a className="summary__btn-pay">Continue &amp; pay</a>
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
