import Head from "next/head";

import Categories from "../../components/Categories";
import Presentation from "../../components/Presentation";

export default function Products() {
  return (
    <>
      <Head>
        <title> – audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Categories />
        <Presentation />
      </section>
    </>
  );
}
