import Head from "next/head";

import Hero from "../components/Hero";
import Index from "../components/Index";

export default function Home() {
  return (
    <>
      <Head>
        <title>audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Index />
    </>
  );
}
